# .github/workflows/publish-configs.yml
name: Publish Config Updates

on:
  push:
    branches: [main]
    paths:
      - 'commands/**'
      - 'agents/**'
      - 'VERSION'
  release:
    types: [published]

jobs:
  notify-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Trigger updates in all repos
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_ADMIN_TOKEN }}
          script: |
            const org = context.repo.owner;
            
            // Get all repos in the org
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org: org,
              type:集'all'
            });
            
            // Trigger update workflow in each repo
            for (const repo of repos) {
              // Skip archived repos and the config repo itself
              if (repo.archived || repo.name === context.repo.repo) continue;
              
              try {
                await github.rest.repos.createDispatchEvent({
                  owner: org,
                  repo: repo.name,
                  event_type: 'claude-config-updated',
                  client_payload: {
                    version: '${{ steps.version.outputs.version }}'
                  }
                });
                console.log(`✅ Triggered update for ${repo.name}`);
              } catch (error) {
                console.log(`⚠️  Failed to trigger ${repo.name}: ${error.message}`);
              }
            }